version: 2.1

orbs:
  python: circleci/python@2.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    description: "Setup Django application and run tests"
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: "Run tests"
          command: python manage.py test

workflows:
    build-and-deploy:
      jobs:
        - build
        - eb/deploy:
            context: aws-credentials
            application-name: exchangeRatesApi2
            environment-name: django-env5
            platform-version: python-3.8
            # filters:
            #   branches:
            #     only:
            #       - main
            # label: version-<<pipeline.number>>
            requires:
              - build